using MappingGenerator.Samples.Mapping.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MappingGenerator.Samples;
namespace MappingGenerator.Samples
{
    public class MapperUser
    {
        private IMapper _mapper;
        public MapperUser(IMapper mapper)
        {
            _mapper = mapper;
        }

        public MappingGenerator.Samples.Domain2.Class1 Work(MappingGenerator.Samples.Domain1.Class1 class1)
        {
            return _mapper.Map((Domain2.Class1 y) => class1);
        }
    }
}
