using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MappingGenerator.Samples.Mapping.AutoGenerated;

namespace MappingGenerator.Samples.Mapping
{
    public class Class2ToClass2Mapper : Mapper3Base
    {
        public Class2ToClass2Mapper(IMapper mapper) : base(mapper)
        {
        }
    }
}
