using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MappingGenerator.Samples.Mapping.AutoGenerated
{
    public class Class1ToClass2PeerMapper : Mapper2Base
    {
        public Class1ToClass2PeerMapper(IMapper mapper) : base(mapper)
        {
        }
    }
}
